add solution for accordion
js-tasks-ru/htmlcss-20220317_artyom1990 pull request #4
Opened 2022-04-10 07:43 UTC by krivenkov90

2022-04-10 07:43 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-12 10:56 UTC, GSemikozov requested changes

2022-04-12 10:56 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__summary_title {
это все-таки элемент а не модификатор, поэтому - .accordion__title

2022-04-12 10:56 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.marker {
элемент блока = .accordion__arrow

2022-04-13 20:15 UTC, GSemikozov approved these changes

2022-04-13 20:15 UTC, merged