add solution for layout
js-tasks-ru/htmlcss-20220317_artyom1990 pull request #5
Opened 2022-04-11 13:23 UTC by krivenkov90

2022-04-11 13:24 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-12 10:59 UTC, GSemikozov requested changes

2022-04-12 10:59 UTC, GSemikozov commented on components/container/container.css
> +    gap: 30px;
либо это не универсальный контейнер (не в любом же контейнеры будут такие отступы), либо блок назван неправильно (если используется только в конкретном кейсе, и хотелось бы из названия компонента понимать что конкретно он делает) - поэтому надо поправить

2022-04-12 10:59 UTC, GSemikozov commented on components/header/header.css
> +    margin-left: 160px;
а зачем слева? контент внутри каждом такой большой секции заворачивается в контейнер)

2022-04-12 10:59 UTC, GSemikozov commented on components/page/page.css
> +.page {
вероятно еще надо height: 100%?

2022-04-12 15:39 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-12 15:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-13 20:17 UTC, GSemikozov requested changes

2022-04-13 20:17 UTC, GSemikozov commented on index.html
> +                <h1 class="header__title">
в каждой из секций не хватает критически важного компонента - container (max-width: 1110px; margin: 0 auto)

2022-04-13 20:49 UTC, krivenkov90 commented on index.html
> +                <h1 class="header__title">
Сделано!!!

2022-04-13 20:49 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-14 11:59 UTC, GSemikozov approved these changes

2022-04-14 11:59 UTC, merged