solution for histogram
js-tasks-ru/htmlcss-20220317_artyom1990 pull request #6
Opened 2022-04-14 20:15 UTC by krivenkov90

2022-04-14 20:15 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-15 19:37 UTC, GSemikozov requested changes

2022-04-15 19:37 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 185px;
высоту лучше не фиксировать

2022-04-15 19:37 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 100%;
и тогда это здесь будет лишним

2022-04-15 19:37 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                    <div class="histogram__view-link">
можно обойтись без лишнего враппера и повесить класс сразу на <a>

2022-04-15 19:37 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    align-items: flex-end;
если здесь зафиксируем высоту, например 50px, то только высота колонок будет зависеть от высоты родителя, а значит можно нормально использовать проценты для указания высоты колонки - от 1 до 100 )

2022-04-19 12:06 UTC, krivenkov90 commented on 04-lection2/01-histogram/histogram.css
> +    height: 185px;
Убрал высоту

2022-04-19 12:06 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-19 12:06 UTC, krivenkov90 commented on 04-lection2/01-histogram/histogram.css
> +    height: 100%;
исправлено

2022-04-19 12:06 UTC, krivenkov90 commented on 04-lection2/01-histogram/index.html
> +                    <div class="histogram__view-link">
исправлено

2022-04-19 12:06 UTC, krivenkov90 commented on 04-lection2/01-histogram/histogram.css
> +    align-items: flex-end;
Сделано

2022-04-19 16:50 UTC, GSemikozov approved these changes

2022-04-19 16:50 UTC, merged