solution for skeleton
js-tasks-ru/htmlcss-20220317_artyom1990 pull request #7
Opened 2022-04-21 16:21 UTC by krivenkov90

2022-04-21 16:22 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-22 09:47 UTC, GSemikozov requested changes

2022-04-22 09:47 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 579px;
ширину и высоту не фиксируем

2022-04-22 09:47 UTC, GSemikozov commented on 04-lection2/02-skeleton/index.html
> +                <div class="skeleton__main-circle skeleton__element_background"></div>
модификаторы нельзя применять в отрыве от тех элементов, которые они модифицируют; соответственно skeleton__element_background должен находиться на одном уровне с skeleton__element, вместо этого - используется рядом с skeleton__main-circle, что является ошибкой реализации

2022-04-22 09:47 UTC, GSemikozov commented on 04-lection2/02-skeleton/index.html
> +                    <div class="skeleton__main_first-line skeleton__element_background"></div>
здесь такая же история с skeleton__main_first-line и skeleton__element_background. Если skeleton__main_first-line - это не модификатор а элемент - тогда исправить класс; если модификатор - тогда надо добавить рядом класс элемента который модифицируем

2022-04-22 09:47 UTC, GSemikozov commented on 04-lection2/02-skeleton/index.html
> +                <div class="skeleton__line-description skeleton__element_background"></div>
та же история с skeleton__element_background

2022-04-22 09:47 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__main_first-line {
уже есть элемент .skeleton__main, и это совсем не линия скелетона)
надо создать отдельный элемент .skeleton__]line, и уже к нему применять модификаторы, который модифицируют только ширину

2022-04-22 09:47 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__line-description {
после оформления .skeleton__line здесь поменять на .skeleton__line_description или .skeleton__line_large

2022-04-22 11:35 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-22 11:35 UTC, krivenkov90 commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__line-description {
Изменил названия классов БЭМ

2022-04-22 12:59 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-23 15:30 UTC, GSemikozov approved these changes

2022-04-23 15:30 UTC, merged